{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "sample-nodejs-openshift.fullname" . }}
  labels:
    {{- include "sample-nodejs-openshift.labels" . | nindent 4 }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host | quote }}
  {{- end }}
  path: {{ .Values.route.path | quote }}
  to:
    kind: Service
    name: {{ include "sample-nodejs-openshift.fullname" . }}
  port:
    targetPort: http
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
  {{- end }}
{{- end }}
